mybatis.type-handlers-package=tw.spring.data.mybatisdemo.handler
mybatis.configuration.map-underscore-to-camel-case=true

# 使用 RowBounds.offset 作為 pageNum
pagehelper.offset-as-page-num=true
# 合理化分頁參數，頁數小於1時查詢第一頁，頁數大於總頁數時查詢最後一頁
pagehelper.reasonable=true
# 允許 pageSize=0，返回所有結果
pagehelper.page-size-zero=true
# 支援通過 Mapper 接口參數來傳遞分頁參數
pagehelper.support-methods-arguments=true